__project_name__ = """caissAI"""
__author__ = """Matthieu Daviaud"""
__email__ = """matthieu.daviaud@gmail.com"""
__version__ = """0.1.0"""
description = """A python project to annotate and comment chess games"""
